/* eslint-disable */

export default [
  {
    'id': 1,
    'name': 'Triella',
    'description': 'Ce médicament est un contraceptif oral (pilule) qui contient un estrogène et un progestatif de première génération. Il est minidosé (moins de 0,04 mg d\'estrogène) et triphasique (tous les comprimés ne contiennent pas la même quantité d\'hormones et sont de trois couleurs différentes).',
    'picture': '', 
    'reimbursed': 100, 
    'generation': 1,
    'type': null, 
    'interruption': false, 
    'laboratory': 'Jassen Cilag',
    'delay_intake': 12,
    'composition': 'Comprimé blanc : Blablabla 0.035mg, 0.035mg\r\n',
    'date': '2021-07-19T14:05:38+02:00',
    'slug': 'pilule1', 
    'created_at': '2021-07-19T14:05:38+02:00',
    'updated_at': null,
    'count_reviews': 0,
  },
  {
    'id': 2,
    'name': 'Minidril',
    'description': 'Description de Minidril',
    'picture': '',
    'reimbursed': 65,
    'generation': 2,
    'type': null,
    'interruption': false,
    'laboratory': 'Majorelle Labo',
    'delay_intake': 12,
    'composition': 'Composition',
    'date': '2021-07-19T14:08:29+02:00',
    'slug': 'pilule2',
    'created_at': '2021-07-19T14:08:29+02:00',
    'updated_at': null,
    'count_reviews': 0,
  },
  {
    'id': 3,
    'name': 'Cerazette',
    'description': 'Cerazette',
    'picture': '',
    'reimbursed': 0,
    'generation': 3,
    'type': null,
    'interruption': true,
    'laboratory': 'MSD France',
    'delay_intake': 12,
    'composition': 'Composition',
    'date': '2021-07-19T14:09:23+02:00',
    'slug': 'pilule3',
    'created_at': '2021-07-19T14:09:23+02:00',
    'updated_at': null,
    'count_reviews': 0,
  },
  {
    'id': 4,
    'name': 'Trinordiol',
    'description': 'Sed eget lobortis odio. Nunc rutrum nisi at ipsum fermentum, quis vestibulum quam tempus. Suspendisse enim orci, finibus eu justo ac, fringilla aliquam mi. Duis iaculis, metus vitae aliquet tempor, diam nibh efficitur tortor, vitae tincidunt lacus arcu quis lectus. Nunc blandit, leo eu viverra commodo, libero quam laoreet turpis, nec commodo nibh libero luctus ipsum. Cras lobortis purus vel euismod efficitur. In sed justo eget leo lobortis iaculis.',
    'picture': '',
    'reimbursed': 65,
    'generation': 2,
    'type': null,
    'interruption': true,
    'laboratory': 'Majorelle Labo',
    'delay_intake': 12,
    'composition': 'La composition de la pilule',
    'date': '2021-07-20T10:23:09+02:00',
    'slug': 'pilule4',
    'created_at': '2021-07-20T10:23:09+02:00',
    'updated_at': null,
    'count_reviews': 0,
  },
  {
    'id': 5,
    'name': 'Cilest',
    'description': 'Aenean at dui in nibh auctor pellentesque et quis mi. Morbi tempus scelerisque enim. Ut ac metus ullamcorper, venenatis velit vitae, feugiat dui. Nulla finibus nisl sed imperdiet ultricies. Mauris vitae erat bibendum mi consequat ullamcorper. Morbi sit amet ultricies lorem. Quisque posuere pellentesque leo eget gravida.',
    'picture': '',
    'reimbursed': 0,
    'generation': 2,
    'type': null,
    'interruption': false,
    'laboratory': 'Jassen Cilag',
    'delay_intake': 12,
    'composition': 'Composition de Cilest',
    'date': '2021-07-20T10:23:55+02:00',
    'slug': 'pilule5',
    'created_at': '2021-07-20T10:23:55+02:00',
    'updated_at': null,
    'count_reviews': 0,
  },
]
